"use client";

import { useEffect, useState } from "react";
import { Calendar, ExternalLink, Loader2 } from "lucide-react";
import { fetchMatterCalendar, type MatterCalendarEvent } from "@/lib/api-client";
import { buildGoogleCalendarUrl } from "@/lib/mobile-calendar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export function MatterCalendarPanel({ matterId }: { matterId: string }) {
  const [events, setEvents] = useState<MatterCalendarEvent[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    void fetchMatterCalendar(matterId)
      .then((d) => setEvents(d.events))
      .finally(() => setLoading(false));
  }, [matterId]);

  if (loading) {
    return <Loader2 className="size-6 animate-spin text-primary" />;
  }

  const upcoming = events.filter((e) => new Date(e.startAt) >= new Date(Date.now() - 86400000));
  const past = events.filter((e) => new Date(e.startAt) < new Date(Date.now() - 86400000));

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold flex items-center gap-2">
          <Calendar className="size-5" />
          Hearings & deadlines
        </h2>
        <p className="text-sm text-muted-foreground">
          Auto-scheduled when you file (341 meeting, debtor education, etc.). Add any event to
          Google Calendar with one tap.
        </p>
      </div>

      {events.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          Calendar fills in when the matter is created and when you Strike The Gavel.
        </p>
      ) : (
        <>
          <EventSection title="Upcoming" events={upcoming} matterId={matterId} />
          {past.length > 0 && <EventSection title="Past" events={past} matterId={matterId} muted />}
        </>
      )}
    </div>
  );
}

function EventSection({
  title,
  events,
  matterId,
  muted,
}: {
  title: string;
  events: MatterCalendarEvent[];
  matterId: string;
  muted?: boolean;
}) {
  if (events.length === 0) return null;

  return (
    <section className={muted ? "opacity-70" : ""}>
      <h3 className="text-sm font-semibold mb-2">{title}</h3>
      <ul className="space-y-2">
        {events.map((ev) => {
          const start = new Date(ev.startAt);
          const gcal = buildGoogleCalendarUrl({
            title: ev.title,
            start,
            durationMin: ev.durationMin,
            details: ev.details,
            location: ev.location,
          });
          return (
            <li key={ev.id} className="rounded-lg border p-3 flex flex-wrap justify-between gap-2">
              <div>
                <p className="font-medium">{ev.title}</p>
                <p className="text-xs text-muted-foreground">
                  {start.toLocaleString(undefined, {
                    weekday: "short",
                    month: "short",
                    day: "numeric",
                    hour: "numeric",
                    minute: "2-digit",
                  })}
                  {ev.location && ` · ${ev.location}`}
                </p>
                {ev.kind === "meeting_341" && (
                  <Badge className="mt-1" variant="secondary">
                    §341 meeting
                  </Badge>
                )}
                {ev.autoGenerated && (
                  <Badge className="mt-1 ml-1" variant="outline">
                    auto
                  </Badge>
                )}
              </div>
              <Button size="sm" variant="secondary" asChild>
                <a href={gcal} target="_blank" rel="noopener noreferrer">
                  <ExternalLink className="size-4" />
                  Google Calendar
                </a>
              </Button>
            </li>
          );
        })}
      </ul>
    </section>
  );
}
