export type CounselingTier = "gold" | "relay" | "vault";
export type CounselingProvider = "debtorcc" | "bkcert" | "advantagecc" | "creditorg";

export interface FirmAccount {
  id: string;
  firmName: string;
  attorneyFirstName: string;
  attorneyLastName: string;
  email: string;
  phone?: string;
  state: string;
  counselingTier: CounselingTier;
  counselingProvider: CounselingProvider;
  agreementVersion: string;
  agreementAcceptedAt: string;
  createdAt: string;
}

const AGREEMENT_VERSION = "2025-06-12-v1";

const firmStore = new Map<string, FirmAccount>();

export function registerFirm(input: {
  firmName: string;
  attorneyFirstName: string;
  attorneyLastName: string;
  email: string;
  phone?: string;
  state?: string;
  counselingTier: CounselingTier;
  counselingProvider: CounselingProvider;
  agreementAccepted: boolean;
}): FirmAccount {
  if (!input.agreementAccepted) {
    throw new Error("Attorney agreement must be accepted");
  }
  const id = crypto.randomUUID();
  const account: FirmAccount = {
    id,
    firmName: input.firmName.trim(),
    attorneyFirstName: input.attorneyFirstName.trim(),
    attorneyLastName: input.attorneyLastName.trim(),
    email: input.email.trim().toLowerCase(),
    phone: input.phone?.trim(),
    state: input.state?.trim() || "CA",
    counselingTier: input.counselingTier,
    counselingProvider: input.counselingProvider,
    agreementVersion: AGREEMENT_VERSION,
    agreementAcceptedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  };
  firmStore.set(id, account);
  firmStore.set(`email:${account.email}`, account);
  return account;
}

export function getFirmByEmail(email: string): FirmAccount | undefined {
  return firmStore.get(`email:${email.toLowerCase()}`);
}

export function getFirm(id: string): FirmAccount | undefined {
  const firm = firmStore.get(id);
  if (firm && !id.startsWith("email:")) return firm;
  return undefined;
}

export function getAgreementText(): string {
  return `MY BANKRUPTCY — ATTORNEY PLATFORM AGREEMENT (${AGREEMENT_VERSION})

1. You are a licensed attorney or authorized staff acting under attorney supervision.
2. You remain solely responsible for all filings, advice, and compliance with local court rules.
3. AI-generated fields require your review and approval before filing.
4. Client counseling certificates must come from AOUST-approved providers.
5. Payment receipts generated by the platform are for your records; you maintain trust accounting compliance.
6. Demo/sandbox e-file does not submit to PACER; production filing requires your CM/ECF credentials.

By accepting, you agree to these terms and our privacy policy.`;
}
