import type { FilingResult } from "@chapterai/efile";

export type BankruptcyEventKind =
  | "consult"
  | "follow_up"
  | "document_deadline"
  | "credit_counseling"
  | "filing_target"
  | "meeting_341"
  | "court_hearing"
  | "fee_payment"
  | "debtor_education";

export interface MatterCalendarEvent {
  id: string;
  kind: BankruptcyEventKind;
  title: string;
  startAt: string;
  durationMin: number;
  details: string;
  location?: string;
  autoGenerated: boolean;
  source: "filing" | "intake" | "manual";
}

function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate + "T10:00:00");
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function atLocalHour(iso: string, hour: number): string {
  const d = new Date(iso);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

/** Post-filing calendar — 341, debtor education, plan payment reminders */
export function buildPostFilingCalendarEvents(input: {
  matterId: string;
  debtorDisplayName: string;
  chapter: "7" | "13";
  filing: FilingResult;
  divisionName?: string;
}): MatterCalendarEvent[] {
  const filingDate = input.filing.filedAt.slice(0, 10);
  const d = input.debtorDisplayName;
  const id = input.matterId;
  const court = input.divisionName ?? "U.S. Bankruptcy Court";

  const events: MatterCalendarEvent[] = [
    {
      id: `cal-341-${id}`,
      kind: "meeting_341",
      title: `341 meeting — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 30), 10),
      durationMin: 60,
      details: `Meeting of creditors (11 U.S.C. §341)\nCase ${input.filing.caseNumber}\nMatter: ${id}\nBring photo ID and SS card · arrive 15 minutes early`,
      location: court,
      autoGenerated: true,
      source: "filing",
    },
    {
      id: `cal-docket-${id}`,
      kind: "follow_up",
      title: `Monitor docket — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 3), 9),
      durationMin: 30,
      details: `Check CM/ECF for trustee reports and motions\nCase ${input.filing.caseNumber}\nMatter: ${id}`,
      autoGenerated: true,
      source: "filing",
    },
  ];

  if (input.chapter === "7") {
    events.push({
      id: `cal-debtor-ed-${id}`,
      kind: "debtor_education",
      title: `Debtor education due — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 45), 9),
      durationMin: 30,
      details: `Complete personal financial management course before discharge (§727(a)(11))\nMatter: ${id}`,
      autoGenerated: true,
      source: "filing",
    });
    events.push({
      id: `cal-discharge-${id}`,
      kind: "court_hearing",
      title: `Discharge eligibility — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 90), 9),
      durationMin: 15,
      details: `Track discharge — confirm no §727 objections\nCase ${input.filing.caseNumber}\nMatter: ${id}`,
      autoGenerated: true,
      source: "filing",
    });
  } else {
    events.push({
      id: `cal-plan-pay-${id}`,
      kind: "fee_payment",
      title: `First plan payment — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 30), 9),
      durationMin: 15,
      details: `Confirm first Ch 13 payment received (§1326)\nMatter: ${id}`,
      autoGenerated: true,
      source: "filing",
    });
    events.push({
      id: `cal-confirmation-${id}`,
      kind: "court_hearing",
      title: `Plan confirmation prep — ${d}`,
      startAt: atLocalHour(addDays(filingDate, 45), 14),
      durationMin: 90,
      details: `Confirmation hearing preparation\nMatter: ${id}`,
      location: court,
      autoGenerated: true,
      source: "filing",
    });
  }

  return events;
}

/** Pre-filing intake milestones */
export function buildIntakeCalendarEvents(input: {
  matterId: string;
  debtorDisplayName: string;
  createdAt: string;
}): MatterCalendarEvent[] {
  const created = input.createdAt.slice(0, 10);
  return [
    {
      id: `cal-docs-${input.matterId}`,
      kind: "document_deadline",
      title: `Documents due — ${input.debtorDisplayName}`,
      startAt: atLocalHour(addDays(created, 14), 17),
      durationMin: 15,
      details: `Client document deadline (ID, paystubs, tax returns)\nMatter: ${input.matterId}`,
      autoGenerated: true,
      source: "intake",
    },
    {
      id: `cal-course1-${input.matterId}`,
      kind: "credit_counseling",
      title: `Course 1 due — ${input.debtorDisplayName}`,
      startAt: atLocalHour(addDays(created, 7), 12),
      durationMin: 30,
      details: `BAPCPA credit counseling before filing\nMatter: ${input.matterId}`,
      autoGenerated: true,
      source: "intake",
    },
  ];
}
