"use client";

import { ExternalLink, FileText, Printer, X } from "lucide-react";
import type { PetitionLineItem, ValuationProvenance } from "@/lib/api-client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const TIER_LABEL: Record<ValuationProvenance["tier"], string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
};

const TIER_VARIANT: Record<
  ValuationProvenance["tier"],
  "success" | "warning" | "default"
> = {
  low: "success",
  medium: "warning",
  high: "default",
};

function formatMoney(amount: string): string {
  const n = parseFloat(amount);
  if (Number.isNaN(n)) return amount;
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

function buildPrintHtml(item: PetitionLineItem, valuation: ValuationProvenance): string {
  const lines = valuation.snapshotLines ?? [];
  const range =
    valuation.lowAmount && valuation.highAmount
      ? `${formatMoney(valuation.lowAmount)} – ${formatMoney(valuation.highAmount)}`
      : "N/A";

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Valuation Memo — ${item.label}</title>
<style>
  body { font-family: Georgia, serif; max-width: 720px; margin: 2rem auto; color: #111; line-height: 1.5; }
  h1 { font-size: 1.25rem; margin-bottom: 0.25rem; }
  .confidential { color: #b45309; font-size: 0.75rem; font-weight: bold; text-transform: uppercase; letter-spacing: 0.05em; }
  .meta { font-size: 0.875rem; color: #444; margin-bottom: 1.5rem; }
  .box { border: 1px solid #ccc; padding: 1rem; background: #fafafa; font-family: ui-monospace, monospace; font-size: 0.8rem; }
  .box p { margin: 0.35rem 0; }
  .highlight { background: #fef3c7; padding: 0.1rem 0.25rem; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #666; border-top: 1px solid #ddd; padding-top: 1rem; }
</style></head><body>
  <p class="confidential">Attorney work product — not filed with the court</p>
  <h1>Asset valuation source memo</h1>
  <p class="meta"><strong>Asset:</strong> ${item.label}<br>
  <strong>Schedule A/B value used:</strong> ${formatMoney(valuation.selectedAmount)} (${TIER_LABEL[valuation.tier]})<br>
  <strong>Source:</strong> ${valuation.sourceName}<br>
  <strong>Lookup date:</strong> ${valuation.lookupDate}<br>
  ${valuation.method ? `<strong>Method:</strong> ${valuation.method}<br>` : ""}
  <strong>Value range on lookup:</strong> ${range}</p>
  <div class="box">
    ${lines.map((l) => `<p>${l.includes("←") ? `<span class="highlight">${l}</span>` : l}</p>`).join("")}
  </div>
  <footer>Generated by My Bankruptcy · ${new Date().toLocaleString()} · Retain in client file if judge challenges valuation.</footer>
</body></html>`;
}

interface ValuationSourceModalProps {
  item: PetitionLineItem;
  debtorName?: string;
  onClose: () => void;
}

export function ValuationSourceModal({ item, debtorName, onClose }: ValuationSourceModalProps) {
  const valuation = item.valuation;
  if (!valuation) return null;

  const handlePrint = () => {
    const html = buildPrintHtml(item, valuation);
    const win = window.open("", "_blank", "width=800,height=900");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
      onClick={onClose}
      role="presentation"
    >
      <div
        className="flex max-h-[90vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-elevated animate-fade-in"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-labelledby="valuation-source-title"
      >
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-primary-muted">
              <FileText className="size-5 text-primary" />
            </div>
            <div>
              <h2 id="valuation-source-title" className="font-display text-lg font-bold">
                Valuation source
              </h2>
              <p className="text-xs text-muted-foreground">{valuation.sourceName}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted"
            aria-label="Close"
          >
            <X className="size-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          <div className="mb-4 flex flex-wrap gap-2">
            <Badge variant={TIER_VARIANT[valuation.tier]}>
              {TIER_LABEL[valuation.tier]} — {formatMoney(valuation.selectedAmount)}
            </Badge>
            {valuation.lowAmount && valuation.mediumAmount && valuation.highAmount && (
              <>
                <Badge variant="outline">Low {formatMoney(valuation.lowAmount)}</Badge>
                <Badge variant="outline">Med {formatMoney(valuation.mediumAmount)}</Badge>
                <Badge variant="outline">High {formatMoney(valuation.highAmount)}</Badge>
              </>
            )}
            <Badge variant="secondary">Lookup {valuation.lookupDate}</Badge>
          </div>

          <p className="mb-3 text-sm text-muted-foreground">
            {debtorName ? `${debtorName} · ` : ""}
            {item.label}
          </p>
          {valuation.method && (
            <p className="mb-4 text-sm">
              <span className="font-semibold">Method: </span>
              {valuation.method}
            </p>
          )}

          <div className="rounded-xl border border-border bg-slate-50 p-6 font-mono text-sm shadow-inner">
            <p className="mb-4 border-b border-border pb-3 font-sans text-base font-bold">
              {valuation.sourceName} — snapshot
            </p>
            <ul className="space-y-2 text-muted-foreground">
              {(valuation.snapshotLines ?? []).map((line) => (
                <li
                  key={line}
                  className={
                    line.includes("←")
                      ? "rounded-md bg-amber-100 px-2 py-1 font-semibold text-amber-950"
                      : undefined
                  }
                >
                  {line}
                </li>
              ))}
            </ul>
          </div>

          {valuation.sourceUrl && (
            <a
              href={valuation.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-4 inline-flex items-center gap-1 text-sm text-primary hover:underline"
            >
              Open original source
              <ExternalLink className="size-3.5" />
            </a>
          )}

          <p className="mt-4 text-xs text-muted-foreground">
            Yellow highlight = the value selected for Schedule A/B. Print the attorney memo to keep
            in the client file if a judge asks where the number came from.
          </p>
        </div>

        <div className="flex flex-wrap gap-2 border-t border-border bg-muted/30 px-6 py-4">
          <Button variant="default" onClick={handlePrint}>
            <Printer className="size-4" />
            Print attorney memo
          </Button>
          <Button variant="secondary" onClick={onClose}>
            Close
          </Button>
        </div>
      </div>
    </div>
  );
}
